version: '3.8'
services:
  app:
    container_name: ai_app
    build: .
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: mongo
    container_name: ai_db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db